name: Register docker image to AWS ECR

on:
  push:
    branches:
      - main
      - feature/add-fargate-infra
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY: deathma-tv-server
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-register:
    name: Register deathma-tv-server image to AWS ECR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure aws cerdentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v1
        id: amazon-ecr-login

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - uses: docker/build-push-action@v3
        with:
          push: true
          context: deathma-tv-server
          platforms: linux/arm64
          tags: ${{ steps.amazon-ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # - name: Build, tag, and push image to Amazon ECR
      #   env:
      #     ECR_REGISTRY: ${{ steps.amazon-ecr-login.outputs.registry }}
      #     ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker buildx build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .--cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache-new,mode=max --platform linux/arm64 --push .
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    needs: build-and-register
    name: Deploy to staging ECS
    runs-on: ubuntu-latest

    steps:
      - name: Configure aws cerdentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/checkout@v3

      - name: Download ecspresso
        uses: kayac/ecspresso@v1
        with:
          version: v1.7.12

      - name: Register task definition
        run: ecspresso --config config.yml register
        working-directory: ./deathma-tv-infra/staging/ecspresso

      - name: Deploy to ecs
        run: ecspresso --config config.yml deploy --latest-task-definition
        working-directory: ./deathma-tv-infra/staging/ecspresso
