name: Check eslint format.
on:
  push:
    paths:
      - "deathma-tv-viewer-web/**/**.js"
      - "deathma-tv-viewer-web/**/**.ts"
      - "deathma-tv-viewer-web/**/**.tsx"

jobs:
  run_eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Node Modules 📦
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: yarn
          cache-dependency-path: "./deathma-tv-viewer-web/yarn.lock"

      - name: yarn install
        run: |
          yarn install --prefer-offline
        working-directory: deathma-tv-viewer-web

      - name: Run eslint
        run: |
          yarn eslint --ext '.js,.ts' --ignore-path .gitignore .
        working-directory: deathma-tv-viewer-web

      - name: Run prettier
        run: |
          yarn prettier --check .
        working-directory: deathma-tv-viewer-web
